name: Delete
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch name
      environment:
        type: string
        description: Environment name

jobs:
  delete-stack:
    name: Delete stack
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack_name:
          - closestwins-storage-${{ github.event.inputs.branch }}-${{ github.event.inputs.environment }}
          - closestwins-api-${{ github.event.inputs.branch }}-${{ github.event.inputs.environment }}
          - closestwins-app-${{ github.event.inputs.branch }}-${{ github.event.inputs.environment }}
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
      - name: Intiate delete stack
        run: aws cloudformation delete-stack --stack-name ${{ martix.stack_name }}
      - name: Wait for the delete confirmation
        run: aws cloudformation wait stack-delete-complete --stack-name ${{ martix.stack_name }}
