name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch name
      environment:
        type: string
        description: Environment name

jobs:
  deploy-storage:
    name: Deploy closest wins storage stack
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout closestwins storage repo
        with:
          name: grishasergii/closestwins-storage
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
      - uses: ./closestwins-storage/actions/deploy
        name: Deploy Storage stack
        with:
          branch: ${{ github.event.inputs.branch }}
          environment: ${{ github.event.inputs.environment }}
          aws_artifacts_bucket: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
          aws_cfn_bucket: ${{ secrets.AWS_CLOSESTWINS_CFN_BUCKET }}
          aws_region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
