name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch name
      environment:
        type: string
        description: Environment name

jobs:
  deploy:
    name: Deploy closest wins stacks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17
      - run: npm i -g meta
        name: Install meta
      - run: meta exec "git checkout ${{ github.event.inputs.branch }}"
      - uses: ./closestwins-storage/.github/workflows/deploy.yml
        name: Deploy Storage stack
        with:
          branch: ${{ github.event.inputs.branch }}
          environment: ${{ github.event.inputs.environment }}
        secrets:
          aws_access_key_id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
          artifacts_bucket: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
          cfn_bucket: ${{ secrets.AWS_CLOSESTWINS_CFN_BUCKET }}
      - uses: ./closestwins-api/.github/workflows/deploy.yml
        name: Deploy API stack
        with:
          branch: ${{ github.event.inputs.branch }}
          environment: ${{ github.event.inputs.environment }}
        secrets:
          aws_access_key_id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
          artifacts_bucket: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
          cfn_bucket: ${{ secrets.AWS_CLOSESTWINS_CFN_BUCKET }}
      - uses: ./closestwins-app/.github/workflows/deploy.yml
        name: Deploy APP stack
        with:
          branch: ${{ github.event.inputs.branch }}
          environment: ${{ github.event.inputs.environment }}
        secrets:
          aws_access_key_id: ${{ secrets.AWS_CLOSESTWINS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_CLOSESTWINS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_CLOSESTWINS_REGION }}
          artifacts_bucket: ${{ secrets.AWS_CLOSESTWINS_ARTIFACTS_BUCKET }}
          cfn_bucket: ${{ secrets.AWS_CLOSESTWINS_CFN_BUCKET }}
          map_api_key: ${{ secrets.MAP_API_KEY }}
