name: Deploy
on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: Branch name
      environment:
        type: string
        description: Environment name

jobs:
  deploy:
    name: Deploy closest wins stacks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout meta repo
      - uses: actions/setup-node@v2
        name: Setup Node.js
        with:
          node-version: 17
      - run: npm i -g meta
        name: Install meta
      - run: meta exec "git checkout ${{ github.event.inputs.branch }}"
        name: Checkout all meta repos
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ secrets.aws_region }}
      - uses: ./closestwins-storage/actions/deploy
        name: Deploy Storage stack
        working-directory: ./closestwins-storage
        with:
          branch: ${{ github.event.inputs.branch }}
          environment: ${{ github.event.inputs.environment }}
          aws_artifacts_bucket: ${{ secrets.aws_artifacts_bucket }}
          aws_cfn_bucket: ${{ secrets.aws_cfn_bucket }}
          aws_region: ${{ secrets.aws_region }}
